### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by jashgopani** [portexe/react-pwr#1]
Hi @portexe, I followed your tutorial and I am getting multiple error, so I tried using your library but it is giving me React not defined error when I try to import the {Requirements} component.
The error is at the import line in the bundled module...
![image](https://user-images.githubusercontent.com/40660648/118441928-86411b80-b707-11eb-9cfb-640b59b5c765.png)

Steps to reproduce:
1. Clone repo and npm install
2. npm run build-lib
3. npm link in this project
4. npm link portexe-react-pwr in my fresh `create-react-app` project

![image](https://user-images.githubusercontent.com/40660648/118442215-f059c080-b707-11eb-9e2c-0b91a82a9ad5.png)

Can you check and resolve this :)

**Comment by mrinab** [comment]
I guess you need to import React from the react library apart from the states.
import React from 'react';
 is what I mean.
In your case, line 1 should be:
import React, {usestate as e...} from 'react';

**Comment by jashgopani** [comment]
@mrinab I tried that too...doesn't work

**Comment by jashgopani** [comment]
And that error is coming in the bundled file generated by rollup. So there must be someway that rollup includes react in the final output also

**Comment by salikansari6** [comment]
I have found the solution. It's a silly error. There are missing import React from 'react' statements in the component files. Once you import it the error is fixed.

**Comment by jashgopani** [comment]
Thanks, @salikansari6 . It works now :)
