### ISSUE TITLE
 Uncaught Error: Invalid hook call. Hooks can only 

### ISSUE THREAD

**Issue by hungdev** [portexe/react-pwr#3]
i tried to use your lib in new react app, but it gets react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/12009276/175765446-b4cc004d-567d-4679-8924-1e69fe8b0f2f.png">

**Comment by hungdev** [comment]
When i publish to npm, it doesnt have,it only appears when i install from local package

**Comment by jv18creator** [comment]
any fixes?

**Comment by hungdev** [comment]
@jv18creator you need to run link react
read here: https://stackoverflow.com/questions/65259040/react-antd-rollup-component-library-error-invalid-hook-call-hooks-can-onl/65259365#65259365
